### ISSUE TITLE
Won't allow user to quit application after error 

### ISSUE THREAD

**Issue by ninjarogue** [bouncetechnologies/Font-Smoothing-Adjuster#35] opened 2022-04-22 08:07 UTC
This is really sketchy.. for some reason there was an error after I hit the enable button and all of sudden I am not allowed to quit the application

**Comment by abyrne10** [comment] 2022-04-22 10:00
Closing this, as it's a duplicate of #36.

**Closed by abyrne10** 2022-04-22 10:00 UTC
Labels: duplicate
